### PR TITLE
Clean up 'uses' ports for TopoFlow components

### PR DESCRIPTION
**Pull request by mdpiper**
From the base **uses.json** files produced by @mperignon's scripts, I made the following changes:

* Changed `met` port id to `meteorology`
* Used an empty JSON array for components with no uses ports (cf. hydrotrend)
* Removed `erode` port id. (Maybe this will be added back if we can figure out what the "erode_d8_global" component is)

### CODE REVIEW

**Comment by mdpiper** [comment]
I'm letting this PR sit for a few minutes, if anyone would like to comment. (I feel so GitHubby.)

**Comment by mcflugen** [comment]
I think the `infil` components can be connected to a component that provides either an `erode` or a
`satzone` provides port. So maybe we should keep the `erode` port?

**Comment by mdpiper** [comment]
That's a good idea. I'll revert 1f857cd.

**Comment by mperignon** [comment]
The way I pulled the variable names and connected them to ports is not the most natural, but I expect that a variable provided by two ports would show up under both ports in the uses file of the port that needs it. I checked by hand but not rigorously, so it's worth looking at that if it looks like components are being too "needy"...

**Comment by mdpiper** [comment]
And this worked perfectly -- `land_surface__elevation` is provided by both "erode" and "satzone", so both ports appeared in the infil components.

**Pull request merged**
