### PR TITLE
Create topoflow component directories, v1 of files

### PR DESCRIPTION
**Pull request by mperignon**
Adds script-generated directories and files for TopoFlow components.

Known issues:
- Missing field values in info.json. Existing taken from parameters.json
- Did not know what to include in provides.json and uses.json. Using dummies
- Lost "Input 1" etc headers in xml -> yaml translation. Rewrite script to preserve them?

### CODE REVIEW

**Comment by mdpiper** [comment]
Thank you, @mperignon; this is excellent! And it will save us a lot of time. 

For the `info.json` file, here are values that can be used for each component:

* "author" : "scott.peckham@colorado.edu"
* "version" : "3.1.0"
* "doi" : "10.1594/IEDA/100174"
* "license" : "Apache"

I can quickly edit the dummy provides and uses ports by hand.

It would be very helpful if you could recover the tab headers (e.g., **Input 1**) from the CMT XML files; we use them as dividers in the WMT interface. See, e.g., HydroTrend's [parameters](https://github.com/mdpiper/component_metadata/blob/master/hydrotrend/db/parameters.json).

I have two other items that I think would appropriate to address in this pull request:

* please lowercase the directory names for the components; e.g., `channels_diffusive_wave` instead of `Channels_Diffusive_Wave`.
* in the `parameters.json` file, please use sentence case for the *description* attribute of each parameter. E.g., "Component status" instead of "component status".

**Comment by mperignon** [comment]
- Script now looks for a text file of extra entries when creating info.json to include those missing values. Could also have it look for a text file with the summaries for each component.
- Tab headers are recovered in both the yaml and json files, and they appear in the correct order
- Capitalization is fixed
- Problems with the formatting of cfg files is fixed

Other possible issues:
- Capitalization of component names with proper nouns or '2D'?
- cfg file writer assumes it's a TopoFlow component (for the header)

**Comment by mperignon** [comment]
Scripts are here:
https://github.com/mperignon/component_creator

**Comment by mdpiper** [comment]
Thank you, @mperignon!

**Pull request merged**
